// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDkU08C5k04BLXpj9_HW9ypn3zO5nRpA94',
    appId: '1:573217891950:ios:e06a518c5bb4f3319b687f',
    messagingSenderId: '573217891950',
    projectId: 'padhle-a58d3',
    storageBucket: 'padhle-a58d3.firebasestorage.app',
    iosBundleId: 'com.example.padho',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBiB8Vs-6grJU3vdIPNFVQfimW7UVweZ8w',
    appId: '1:573217891950:web:38127c0d23d089c89b687f',
    messagingSenderId: '573217891950',
    projectId: 'padhle-a58d3',
    authDomain: 'padhle-a58d3.firebaseapp.com',
    storageBucket: 'padhle-a58d3.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDuWetk3cV8_8NYp2HmFRhXQGwPrtlTo34',
    appId: '1:573217891950:android:9afc47074e26e2059b687f',
    messagingSenderId: '573217891950',
    projectId: 'padhle-a58d3',
    storageBucket: 'padhle-a58d3.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBiB8Vs-6grJU3vdIPNFVQfimW7UVweZ8w',
    appId: '1:573217891950:web:842be3f4312c8fa19b687f',
    messagingSenderId: '573217891950',
    projectId: 'padhle-a58d3',
    authDomain: 'padhle-a58d3.firebaseapp.com',
    storageBucket: 'padhle-a58d3.firebasestorage.app',
  );
}
